### ISSUE TITLE
It would be a nice addition to know which tests in a set were re run

### ISSUE THREAD

**Issue by bill2605** [prashant-ramcharan/courgette-jvm#95] opened 2019-01-03 21:58 UTC
This is more of a feature request.
If the rerun failure flag is enabled, it would be good to know which tests we ran twice. Right now the report simply shows the number of test in the rerun section but does not allow for the user to click on it in order to list tests that required a second run. 

To that point, it would be also nice to know why said tests required a rerun - generating an error log for the failed test as well as a new log for the test re run.

ex
Test name -> Click on Button Foo
- test fails due to `NoSuchElementException` for button `Foo` -> create section in log/entry in the report xml for this initial failure to be captured (click_on_button_foo.log)
- run test again -> create new log/entry in report xml for second outcome (click_on_button_foo_rerun.log)

You would get more information about your test knowing if the rerun was caused by the same failing step, env issue, etc..

**Comment by prashant-ramcharan** [comment] 2019-01-04 12:11
Courgette doesn't create / modify any of the core reports generated by Cucumber so by updating the report(s) to include re-run info would be somewhat complicated post completion of all theads.

Currently it collects and saves the multithreaded reports (json, html and xml) into a single report at the end of the test run. 

I may look into adding a new status to the Courgette html report to flag a test that passes after a re-run.

_______
 _Might be useful_

If you use Team City as your CI, there is a plugin that uses the results from Cucumber.xml and reports on flaky tests over time.

https://confluence.jetbrains.com/display/TCD18/Viewing+Tests+and+Configuration+Problems#ViewingTestsandConfigurationProblems-FlakyTests

**Comment by prashant-ramcharan** [comment] 2019-01-04 21:05
This is now released in version 3.1.0.

You can now:

* Filter reruns in the Courgette html report by clicking the rerun section.
* See which scenarios passed or failed after a rerun.

![courgettejvm_report](https://user-images.githubusercontent.com/2563149/50710954-6774e980-1064-11e9-97ad-740f6c2a5620.png)
   
Unfortunately, logging 2 tests outcomes is not within the scope of Courgette.

You can still view the stack trace and screenshot for the test failures via the Courgette and Cucumber reports but there's no scope within Courgette to determine whether flaky tests are caused by Selenium, environmental issues etc...

**Comment by bill2605** [comment] 2019-01-04 22:49
This is a great work around! as long as we get some view into which tests required a rerun and the outcome, all is well!

Cheers man

**Closed** 2019-01-05 02:52 UTC
Labels: enhancement, released
