### ISSUE TITLE
Does not run on Windows machine.

### ISSUE THREAD

**Issue by evanliferock** [prashant-ramcharan/courgette-jvm#81] opened 2018-10-16 19:58 UTC
When running on a windows machine this error is produced.

```
    java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long
    	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    	at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:27)
    	at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:143)
    	at courgette.runtime.CourgetteRunner.lambda$run$1(CourgetteRunner.java:47)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
    	at java.lang.ProcessImpl.create(Native Method)
    	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
    	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
    	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    	... 7 more
```

Here's the runner suite.

```
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 10,
        runLevel = CourgetteRunLevel.FEATURE,
        rerunFailedScenarios = true,
        showTestOutput = true,
        reportTargetDir = "build",
        cucumberOptions = @CucumberOptions(
                glue = "com.sap.automation",
                features = "classpath:features",
                plugin = {
                        "pretty",
                        "html:target/cucumber-html-report",
                        "json:target/cucumber-reports/Cucumber.json",
                        "junit:target/cucumber-reports/Cucumber.xml"},
                monochrome = true
        ))
```

**Comment by prashant-ramcharan** [comment] 2018-10-16 20:37
Courgette does work on Windows machines but the classpath on your Windows machine is too long. This is not an issue on linux or mac.

Read / follow the suggestions here:
https://wiki.pentaho.com/display/ServerDoc2x/Working+around+long+Classpath+issue+in+Windows

_or_ 

Upgrade to Java 9 / 10 and the issue should be resolved because Courgette uses the Java Platform Module System instead of building a classpath.

**Comment by prashant-ramcharan** [comment] 2018-10-17 12:08
Also, change the features path to a relative directory path instead of the classpath.

Change this:
````java
features = "classpath:features"
````

to:

````java
features = "src/test/resources/features"
````

**Comment by evanliferock** [comment] 2018-10-18 20:07
Ah gotcha! I am using Gradle and have tried to implement the changes you have suggested. Unfortunately Gradle seems to be unwilling to read the classpath from a Manifest file in a JAR. I've just tried to get it running on my Mac first. I've tried a whole bunch of things
```
task testPathingJar(type: Jar) {
    appendix = "testPathing"
    doFirst {
        manifest {
            attributes "Class-Path": "/Users/evan/Repos/quality-management-system/build/classes/java/test/ "
                    .plus("/Users/evan/Repos/quality-management-system/build/resources/test/ ")
                    .plus("/Users/evan/Repos/quality-management-system/build/classes/java/main ")
                    .plus("/Users/evan/Repos/quality-management-system/build/resources/main ")
                                    .plus(configurations.testRuntime.files*.path.join(" "))
        }
    }
}

compileTestJava {
    dependsOn(testPathingJar)
    classpath = files(testPathingJar.outputs.files)
}
```
With this it's unable to compile and can't find any of the dependencies
OR instead of putting it in the task 

```
task wip(type: RunTest) {
    description 'Run work in progress tests'
    classpath = project.tasks.testPathingJar.outputs.files
    systemProperties["cucumber.tags"] = "@wip"
}
```
I then get
```
com.sap.automation.stepdefinitions.RunTestSuite > initializationError FAILED
    java.lang.ClassNotFoundException
```
Part of the stacktrace
```
java.lang.ClassNotFoundException: com.sap.automation.stepdefinitions.RunTestSuite
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:67)
```
This is maybe not a Courgette issue so if you don't have any suggestions feel free to close this issue.

**Comment by prashant-ramcharan** [comment] 2018-10-18 21:08
If you using your **Mac** - you don't need to use a manifest file or build the classpath yourself, Courgette will do this for you.

This is only an issue on **Windows** when using Courgette with Java 8. 

Courgette with Java 9 / 10 should work fine!

Perhaps try the example project: https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by prashant-ramcharan** [comment] 2018-10-18 21:34
If you provide an example project which can reproduce this issue on a Mac as well, I can take a look but it sounds like you facing other non Courgette related issues.

I'll close this issue but feel free to re-open it if you find that your errors are related to Courgette.

**Closed** 2018-10-18 21:44 UTC

**Comment by evanliferock** [comment] 2019-02-07 18:46
I ended up fixing this by changing source & target compatibility to Java 10 as well as using this plugin: https://plugins.gradle.org/plugin/com.virgo47.ClasspathJar

**Comment by prashant-ramcharan** [comment] 2019-02-07 19:31
Excellent - thanks for the update @evanliferock

**Comment by titudatta11370** [comment] 2019-12-20 19:39
Hi @evanliferock could you explain little more how you resolved this issue? I am facing the same. I am new to gradle but I tried using the plugin you mentioned and changing the source and target, does not seem to be working. FYI Its a windows machine, when I run "gradle clean test" no tests run.

**Comment by prashant-ramcharan** [comment] 2020-03-19 00:31
You can use Courgette version 4.3.4 with the new Courgette option:

````java
        shortenJavaClassPath = true
````

**Comment by hemachandraraok** [comment] 2020-08-07 21:55
Hi, is this option still available?

**Comment by prashant-ramcharan** [comment] 2020-08-07 22:02
Hello @hemachandraraok 

This option is no longer needed because Courgette no longer builds the classpath. This means you won't get the classpath error on Windows OS anymore. This change was made in version 4.5.0

**Comment by hemachandraraok** [comment] 2020-08-07 22:08
Thank you Prashant. I'm using verison 5.0.0 and getting the same error n Wndows 7. Do you think I think Downgrade?

**Comment by prashant-ramcharan** [comment] 2020-08-07 22:15
That's odd that you still getting the error. 

You shouldn't need to downgrade because that area of code hasn't changed in version 5 but you could try downgrading and see what happens.

Can you run your tests normally using a cucumber runner / cucumber IDE plugin?

**Comment by hemachandraraok** [comment] 2020-08-07 22:17
Yes, the test runs if I just execute the junit runner directly through IDE(intellij). The error happens only when I try to execute using  maven surefire. (mvn test).

**Comment by prashant-ramcharan** [comment] 2020-08-07 22:23
Not sure if you already looked at the advice about the classpath issues with maven, but you can check it out here: https://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html

**Comment by hemachandraraok** [comment] 2020-08-07 23:16
tried various options mentioned in the link..still no luck...

**Comment by hemachandraraok** [comment] 2020-08-08 17:16
Resolved it by mapping a drive (say M:) to point to maven .m2 repository and specifying <localRepository>M:</localRepository> in settings.xml

**Comment by prashant-ramcharan** [comment] 2021-02-04 12:13
**Update**: There is a workaround for this in Courgette version `5.9.2` that accepts a `custom class path`.

See example project here: https://github.com/prashant-ramcharan/courgette-jvm-classpath-example
