### ISSUE TITLE
Reporting issue

### ISSUE THREAD

**Issue by ubobur95** [prashant-ramcharan/courgette-jvm#84] opened 2018-11-12 22:21 UTC
java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at courgette.runtime.CourgetteReporter.formatXmlReport(CourgetteReporter.java:146)
	at courgette.runtime.CourgetteReporter.createReport(CourgetteReporter.java:79)
	at courgette.runtime.CourgetteRunner.lambda$createReport$2(CourgetteRunner.java:110)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at courgette.runtime.CourgetteRunner.createReport(CourgetteRunner.java:108)
	at courgette.api.junit.Courgette.run(Courgette.java:94)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by prashant-ramcharan** [comment] 2018-11-13 09:15
1. Please share the code snippet of your Courgette runner?
2. Can you describe how to re-create this issue?

**Comment by ubobur95** [comment] 2018-11-13 14:52
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 1,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = false,
        showTestOutput = true,
        reportTargetDir = "build",
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources/features",
                glue = "step_defs",
                tags = {"@test"},
                plugin = {
                        "pretty",
                        "json:build/cucumber-report/cucumber.json",
                        "html:build/cucumber-report/cucumber.html",
                        "junit:build/cucumber-report/cucumber.xml"},
                strict = false
        ))
public class RegressionTestSuite {
}

**Comment by ubobur95** [comment] 2018-11-13 15:05
I am trying to use this for mobile testing.
When driver cannot find some element it gives me this.
org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy

**Comment by prashant-ramcharan** [comment] 2018-11-13 16:00
> I am trying to use this for mobile testing.
> When driver cannot find some element it gives me this.
> org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy

This is Selenium related and out of scope for Courgette.


> I tried using testng and it is working fine. The problem is with junit.

If you remove this line from the runner, you won't see this issue.
````java
"junit:build/cucumber-report/cucumber.xml"}
````
Having said that, I cannot reproduce this issue on my side with the junit plugin.

Can you reproduce this with the example project?
https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by prashant-ramcharan** [comment] 2018-11-18 10:04
Closing issue as no further response.

**Comment by bill2605** [comment] 2018-12-21 18:01
Hi, I am currently experiencing this issue as well
`@RunWith(Courgette.class)
@CourgetteOptions(
		threads = 2,
		runLevel = CourgetteRunLevel.SCENARIO,
		rerunFailedScenarios = false,
		showTestOutput = true,
		cucumberOptions = @CucumberOptions(
				features = { "src/test/resources/features" },
				glue = { "com.workjam.stepdefinition" },
				plugin = {
						"pretty:target/cucumber-report/cucumber-pretty.txt",
						"json:target/cucumber-report/cucumber.json",
						"html:target/cucumber-report/cucumber.html",
						"junit:target/cucumber-report/cucumber.xml",
				},
				tags = { "@WebReady" }
		)
)
public class CourgetteTestRun extends BaseContextConfiguration
{
}`

results in 
`java.util.MissingFormatArgumentException: Format specifier '%e'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at courgette.runtime.CourgetteReporter.formatXmlReport(CourgetteReporter.java:146)
	at courgette.runtime.CourgetteReporter.createReport(CourgetteReporter.java:79)
	at courgette.runtime.CourgetteRunner.lambda$createReport$2(CourgetteRunner.java:110)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at courgette.runtime.CourgetteRunner.createReport(CourgetteRunner.java:108)
	at courgette.api.junit.Courgette.run(Courgette.java:99)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

note that i am using ver 3.0.0 of your library and junit 4.1.2.

**Comment by prashant-ramcharan** [comment] 2018-12-21 18:05
Please provide a project that can reproduce this issue as I’m unable to reproduce this?

Does this only happen when running in IntelliJ or does it also happen when run using a gradle task?

**Comment by bill2605** [comment] 2018-12-21 18:14
I'm not sure i can provide the project as it has company information not meant for the public..
this happens when running in IntelliJ as well as when running it only with gradle (let it be gradle test or the custom gradle task for the courgette runner).
If i remove the plugin junit, it will work, however i do need the junit report for other project tasks.
does the courgette runner generate a xml report of the run? if so where could i find it? i tried looking into the folder from the courgette report without any success.

**Comment by prashant-ramcharan** [comment] 2018-12-21 18:54
Unfortunately, Courgette does not generate a xml report. 

I noticed that your runner is extending class BaseContextConfiguration, can you try removing this inheritance to see if it makes any difference?

Can you reproduce this with the Courgette example project or any other non confidential project?

**Comment by bill2605** [comment] 2018-12-21 19:02
BaseContext doesnt impact test run, it only helps with springboot related tasks.

Upon investigating your code and my logs, i see the following possible issue

In private method formatXmlReport in class CourgetteReporter.java :
` return String.format(xmlBuilder.toString(), failures, skipped, tests, time);`

now looking at my logs that the above parses i see the following:
`<testcase classname="Channels" name="Admin can create a new Channel 2" time="180.73117">
<failure message="org.openqa.selenium.TimeoutException: Expected condition failed: waiting for invisibility of [[ChromeDriver: chrome on MAC (f9ef46cfbafbf77613f445aa180fa36c)] -&gt; xpath: //div/descendant::i[contains(@class, 'icon-workjam-dot-2 primary')]] (tried for 80 second(s) with 2000 milliseconds interval)&#10;Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'&#10;System info: host: 'C02V40X4HV2V', ip: 'fe80:0:0:0:1488:527e:75f0:5b78%en0',`

The above is just a snippet but when you search through it you see `%e`.. and the error shared in my previous post was 
`java.util.MissingFormatArgumentException: Format specifier '%e' at `

it seems like the String.format call tries to format %e without any provided values..

Do you have a way to enforce String.Format only for the string   -> 
`<testsuite failures="%d" name="cucumber.runtime.formatter.JUnitFormatter" skipped="%d" tests="%d" time="%f">` from the xml generated?
this might be able to address this issue

**Comment by prashant-ramcharan** [comment] 2018-12-21 19:11
Ah okay I see the issue -- will provide a fix.

**Comment by bill2605** [comment] 2018-12-21 19:17
thanks a lot Prashant!

**Comment by prashant-ramcharan** [comment] 2018-12-21 19:33
Can you retry with this version?

````gradle
repositories {
    jcenter()
}

dependencies {
    testCompile 'io.github.prashant-ramcharan:courgette-jvm:3.0.1-snapshot'
}
````

**Comment by bill2605** [comment] 2018-12-21 19:48
tested on my side and it's looking good :)

**Comment by prashant-ramcharan** [comment] 2018-12-21 19:49
Will prepare a release.

**Comment by prashant-ramcharan** [comment] 2018-12-21 20:00
This is now released.

**Comment by bill2605** [comment] 2018-12-21 20:05
thanks for the QUICK fix :)

**Closed** 2018-12-21 20:08 UTC
Labels: released
