### ISSUE TITLE
With Courgette 1.4.0 unable to see report with all features

### ISSUE THREAD

**Issue by amitmindstix** [prashant-ramcharan/courgette-jvm#13] opened 2017-11-23 11:45 UTC
`@RunWith(Courgette.class)
@CourgetteOptions(
	    runLevel = CourgetteRunLevel.FEATURE,
	    showTestOutput = true,
	    cucumberOptions = @CucumberOptions(
	    		  features = "src/test/resources/com.abc.feature",
	    		  tags = "@abc",
	    		  dryRun = false,
	    		  strict = true,
	    		  monochrome=true,
	    		  glue = "com.abc.stepdefinition",
	    		  plugin = {"pretty", "html:build/reports/cucumberreport/cucumber",
	    		                  "json:build/reports/cucumberreport/cucumber.json" }
	    		))`

With above setup, and 4 feature files under testing it is observed that the final report only contains only details of one feature file. Seemingly the last feature file that completes is the one that is reflecting in the final report. Does courgette manage reporting in a threadsafe way automatically? I mean how does the cucumber.json gets written to disk when there are multiple threads generating the test output?
I see an issue in case of ours where the output of one thread that completes first gets overwritten by the subsequent one.

**Comment by prashant-ramcharan** [comment] 2017-11-23 12:03
This has been reported before and have commented here: https://github.com/prashant-ramcharan/courgette-jvm/issues/7#issuecomment-330063956

Reporting is thread safe. Each report is generated in its own thread then collected and processed after all threads are compete. This isn’t an issue with threads, it’s an issue when running on feature level with rerunFailedScenarios set to true.
If you set this to false, you’d notice it’s not an issue.

My suggestion would be to run on a scenario level.

If you do decide to use feature level and set rerunFailedScenarios to true then it’s best to use Courgette html report that was released in version 1.4.0

**Comment by prashant-ramcharan** [comment] 2017-11-23 12:05
Try with CourgetteRunLevel.SCENARIO

**Comment by amitmindstix** [comment] 2017-11-23 12:21
THanks a lot for quick response. We have not set rerunFailedScenarios in the options.
Is the default true? We can set it to false if that makes it correctly work.

**Comment by prashant-ramcharan** [comment] 2017-11-23 12:27
Default is false. 

Did you try with the example project? 
https://github.com/prashant-ramcharan/courgette-jvm-example

If you can reproduce with this, let me know.

**Comment by prashant-ramcharan** [comment] 2017-11-23 12:29
Are all feature files / feature name the same?

**Comment by amitmindstix** [comment] 2017-11-23 12:36
No the feature file and feature names are different

**Comment by amitmindstix** [comment] 2017-11-23 12:37
Strange thing is this works on development machine well. When we try this on Jenkins server, we encounter this issue. Even on Jenkins this was working some days back and started breaking recently.

**Comment by prashant-ramcharan** [comment] 2017-11-23 18:00
Given that it works locally and worked on Jenkins a few days ago, I'm closing this issue.

There are no recent changes to the library that could have caused this issue you see in Jenkins.

**Comment by amitmindstix** [comment] 2017-11-23 18:17
Apologies for confusion but it is consistently not working now in all environments.

**Comment by prashant-ramcharan** [comment] 2017-11-23 18:19
Please provide the project or sample project on github that I can run myself as I'm not able to reproduce this.

**Comment by amitmindstix** [comment] 2017-11-23 18:21
Is there a way I can get you more useful debug information that can help find root cause of the issue?

**Comment by amitmindstix** [comment] 2017-11-23 18:22
Unfortunately I cannot share the codebase as is.

**Comment by prashant-ramcharan** [comment] 2017-11-23 18:27
Paste the cucumber html + json reports as well as the courgette report which should be in the target folder.

**If it was working a few days ago and now its not**, I don't see how this could suddenly be an issue in the library given that there are no changes.

**Comment by amitmindstix** [comment] 2017-11-23 18:29
the only difference is number of feature files. earlier they were 2 now they are 4.

**Comment by prashant-ramcharan** [comment] 2017-11-23 18:43
Without seeing your feature files (name, path etc..) or test setup, I'm unable to provide any resolution.

As previously mentioned, paste or attach the cucumber html + json reports and courgette report so that I can see what features + lines numbers are run.

Failing that, I'd suggest you debug your code against the Courgette library.

**Comment by prashant-ramcharan** [comment] 2017-11-23 18:46
I'm unable to reproduce this, so I cant fix something thats not broken for me and the vast majority of users of this library.

**Closed by prashant-ramcharan** 2017-11-23 18:46 UTC
