### ISSUE TITLE
Need to bring up test case Id in courgette report

### ISSUE THREAD

**Issue by KannanPandi** [prashant-ramcharan/courgette-jvm#273] opened 2021-03-24 19:09 UTC
Hi Ram,

As we are using courgette plugin for our maven project , in Courgette report we are only getting test case name if we execute our test case in CourgetteRunLevel.SCENARIO

![image](https://user-images.githubusercontent.com/59192407/112369704-7f4aed80-8d02-11eb-8f9e-8dd424a4e835.png)

we need to include this test case id in our report , is there a way to include this ??
![image](https://user-images.githubusercontent.com/59192407/112369489-3dba4280-8d02-11eb-9f1c-160ca111d58c.png)

**Comment by prashant-ramcharan** [comment] 2021-03-25 15:25
Hello,

Showing the feature name -> scenario name in the Courgette report is by design.

I think you referring to Cucumber tags. This not a test case ID and a scenario / feature can have multiple tags.

I can add the tags to the Courgette report when you open each scenario modal but not in the table shown above.

**Comment by prashant-ramcharan** [comment] 2021-03-25 19:22
Something like this:

<img width="854" alt="Screenshot 2021-03-25 at 19 21 04" src="https://user-images.githubusercontent.com/2563149/112531424-765c2980-8d9f-11eb-9d83-fd2a69694c1d.png">

**Comment by prashant-ramcharan** [comment] 2021-04-22 20:40
This is now released in Courgette version `5.11.0`

Tags will be displayed below each scenario as shown below

![courgette-273](https://user-images.githubusercontent.com/2563149/115782094-2cbd2980-a3b3-11eb-8ba2-9b3eade238ad.png)

**Closed** 2021-04-26 07:24 UTC
