### ISSUE TITLE
 java.lang.OutOfMemoryError at Courgette.java:54

### ISSUE THREAD

**Issue by natfatykhova** [prashant-ramcharan/courgette-jvm#214] opened 2020-09-25 11:40 UTC
Hello,

I'm currently upgrading to version 5.4.0, and I'm getting an error when building report:
`RunGhostTests > courgette.api.junit.Courgette.[some tests] FAILED
    courgette.runtime.CourgetteTestFailureException
    java.lang.OutOfMemoryError at Courgette.java:54

5 tests completed, 1 failed`

Could you please advice what could be the cause. I'm getting this for new version only, everything works fine when I run same tests on an old branch with version 3. Thanks

**Comment by prashant-ramcharan** [comment] 2020-09-25 16:54
Hello,

Unfortunately, I cannot reproduce this.

- How much free memory do you have before you start running the tests?
- Are you running the tests using Maven or Gradle?
- Are you running the tests on an IDE like IntelliJ?
- Does this happen all the time?
- Can you try increasing the heap size? (e.g by passing JVM option `-Xmx1g`)  [more info](https://docs.oracle.com/html/E23737_01/configuring_jvm.htm)

**Comment by natfatykhova** [comment] 2020-09-25 17:01
It happens when I run a set of 20+ tests, scenario level. 
Same thing locally (IntelliJ, Macbook Pro, 16Gb) and remotely in Jenkins. 
I tried with `-Dcourgette.vmoptions="-Xms256m -Xmx512m"` but same result...

Is there an option to switch off courgette report? I need only cucumber.json for internal use.

**Comment by prashant-ramcharan** [comment] 2020-09-25 17:15
Courgette line 54 creates the **Cucumber reports** and not the Courgette report.

I just ran 20+ tests and both Cucumber and Courgette reports are created.

- How many threads are you using? 
- Does it also happen using feature run level?



![screencapture-localhost-63342-courgette-jvm-example-build-cucumber-report-cucumber-html-2020-09-25-18_10_51](https://user-images.githubusercontent.com/2563149/94296506-d9891280-ff5a-11ea-9375-4a865e929157.png)


![screencapture-localhost-63342-courgette-jvm-example-build-courgette-report-index-html-2020-09-25-18_07_49](https://user-images.githubusercontent.com/2563149/94296475-cd9d5080-ff5a-11ea-95bc-649ff0ae428e.png)

**Comment by prashant-ramcharan** [comment] 2020-09-25 17:16
Do you have a zipped project or git repo I can reproduce this on?

**Comment by prashant-ramcharan** [comment] 2020-09-25 17:20
Locally, can you also try setting the heap size in your IntelliJ run configuration?

<img width="799" alt="Screenshot 2020-09-25 at 18 18 56" src="https://user-images.githubusercontent.com/2563149/94297045-c32f8680-ff5b-11ea-8d14-8a296fada5dc.png">

**Comment by natfatykhova** [comment] 2020-09-25 18:10
Thanks a lot for your advice. I tried both feature and scenario level, makes no difference. Unfortunately I can't share this project. It looks like the problem could be in reports being too large on my side... For the last run I've got 7Mb `cucumber.json` and 28Mb `cucumber.html` (not sure if it's normal or large?). Let me play with VM Options, hopefully that will help.

**Comment by prashant-ramcharan** [comment] 2020-09-25 18:54
28mb html report is quite large. I assume you saving a lot of images to the report?

**Comment by natfatykhova** [comment] 2020-11-13 12:39
Hi, just an update on the issue, could be a Cucumber problem: https://github.com/cucumber/cucumber/issues/1232
Looking forward for 6.9.0 update. Thanks!

**Comment by prashant-ramcharan** [comment] 2020-11-15 10:52
@natfatykhova This update is now released in Courgette version `5.7.0`

**Comment by natfatykhova** [comment] 2020-11-17 09:45
Thank you @prashant-ramcharan !
I tried with new version, but it failed again with 
`RunGhostTests > courgette.api.junit.Courgette.Testcase name FAILED
    courgette.runtime.CourgetteTestFailureException
    java.lang.OutOfMemoryError at Courgette.java:53`

Current memory setting are `org.gradle.jvmargs=-Xms2G -Xmx2G -XX:+HeapDumpOnOutOfMemoryError`

I tried again with Courgette off, just direct Cucumber, and it passed without exception... Could it be a memory leak, visible only for large projects? 
Thanks.

**Comment by prashant-ramcharan** [comment] 2020-11-17 10:03
Hi  @natfatykhova 

How many tests are your running and how big (in size) is your Cucumber reports?

Can you try the following and check if you get the same error?

1. Try removing the Cucumber reports plugins from your Courgette runner?

2. Run the Courgette runner directly from your IDE and pass VM options.
````
-Xms2048m -Xmx4096m
````

**Comment by prashant-ramcharan** [comment] 2020-11-17 11:48
@natfatykhova I'm now able to reproduce this. 

The OOME is being thrown at `AbstractStringBuilder.ensureCapacityInternal()`

````java
    /**
     * If {@code minimumCapacity} is non positive due to numeric
     * overflow, this method throws {@code OutOfMemoryError}.
     */
    private void ensureCapacityInternal(int minimumCapacity) {
    }
````

I will look into resolving this.

**Comment by natfatykhova** [comment] 2020-11-17 11:54
Ok cool, thanks for update.

**Comment by prashant-ramcharan** [comment] 2020-11-22 23:49
@natfatykhova The out of memory error should be resolved in version `5.8.0`

Please let me know if it fixes your issue.

**Comment by natfatykhova** [comment] 2020-11-23 12:43
@prashant-ramcharan Thank you, that's great, I've run regression on a new built, it's all good -- didn't get OOM error. 
Quick question, looks like now there's a `courgette.runtime.CourgetteTestFailureException` added to logs for every failed feature, is it? Don't remember seeing it before.

**Comment by prashant-ramcharan** [comment] 2020-11-23 12:44
That's great @natfatykhova 

Do you mind posting the courgette exception here?

**Comment by natfatykhova** [comment] 2020-11-23 12:47
That's what I'm getting in console output for Jenkins build, for failed features only (fail is expected here):

RunGhostTests > courgette.api.junit.Courgette.Testcase1 FAILED
    courgette.runtime.CourgetteTestFailureException
    courgette.runtime.CourgetteTestFailureException

RunGhostTests > courgette.api.junit.Courgette.Testcase2 FAILED
    courgette.runtime.CourgetteTestFailureException

RunGhostTests > courgette.api.junit.Courgette.Testcase3 FAILED
    courgette.runtime.CourgetteTestFailureException
    courgette.runtime.CourgetteTestFailureException

RunGhostTests > courgette.api.junit.Courgette.Testcases4 FAILED
    courgette.runtime.CourgetteTestFailureException

RunGhostTests > courgette.api.junit.Courgette.Testcase5 FAILED
    courgette.runtime.CourgetteTestFailureException
    courgette.runtime.CourgetteTestFailureException
    courgette.runtime.CourgetteTestFailureException
    courgette.runtime.CourgetteTestFailureException
    courgette.runtime.CourgetteTestFailureException

RunGhostTests > courgette.api.junit.Courgette.Testcase6 FAILED
    courgette.runtime.CourgetteTestFailureException

> Task :runGhostTests FAILED
8 actionable tasks: 8 executed

**Comment by natfatykhova** [comment] 2020-11-23 12:48
Seems to be an exception for every failed scenario in feature

**Comment by prashant-ramcharan** [comment] 2020-11-23 13:21
Ah you using the Junit runner. 

Yes, this has always printed the exception when there was a failures.

https://github.com/prashant-ramcharan/courgette-jvm/blob/master/src/main/java/courgette/runtime/junit/CourgetteJUnitRunner.java#L90

This was not changed in version in `5.8.0`

**Comment by prashant-ramcharan** [comment] 2020-11-23 13:24
I think the reason why you didn't see it before was because your tests didn't reach that point because of the OOM error.

**Comment by natfatykhova** [comment] 2020-11-23 16:19
Yeah, that makes sense. Thank you.

**Closed** 2020-11-23 18:16 UTC
Labels: bug, fixed, released
