### ISSUE TITLE
How to handle skipped tests cases?

### ISSUE THREAD

**Issue by jiteshk11** [prashant-ramcharan/courgette-jvm#269] opened 2021-03-22 15:08 UTC
As Courgette has capability of re-running failed tests, how can I make sure same for skipped tests (that may happen due to some local infrastructure issues).

**Comment by prashant-ramcharan** [comment] 2021-03-22 19:15
What would cause the tests to skip in the first place and what would re-running of a skipped test accomplish? Would the re-run fix the local infrastructure issues?

If tests are only skipped when there is a local infrastructure issue then perhaps this is the area you need to fix (i.e. the root cause). 

Re-running a skipped tests is an anti-pattern. Your tests should either run and pass or run and fail. If your tests run and skip  "sometimes" then you should address the underlying issue and fix this instead of putting workarounds in your test.

**Comment by jiteshk11** [comment] 2021-03-22 19:24
Thanks Prashant for prominent reply. 

The actual issue is, I am running tests on 3rd party cloud infrastructure, and 5% are tests are always skipped when there is network connection issues. I was thinking if there could be a way to re-run them since those tests never get chance to execute.

**Comment by prashant-ramcharan** [comment] 2021-03-22 19:27
Would it be possible to add a check in a Cucumber before hook to check for connection issues? 

If there is a connection issue then throw an exception. This would cause the test to fail and Courgette will automatically re-run it.

**Comment by prashant-ramcharan** [comment] 2021-03-30 08:15
Closing issue as no further response received.

**Closed by prashant-ramcharan** 2021-03-30 08:15 UTC
