### ISSUE TITLE
Cant use with Maven project

### ISSUE THREAD

**Issue by sundeepsqa** [prashant-ramcharan/courgette-jvm#70] opened 2018-08-27 22:34 UTC
When I try using this with Maven project, I get the following errors:

`Class<Courgette> cannot be resolved to a type`

`CourgetteRunLevel cannot be resolved to a variable`

I have added the repository and dependency specified but I don't get it working.

**Comment by prashant-ramcharan** [comment] 2018-08-28 06:49
Please share your Maven pom.xml

**Comment by prashant-ramcharan** [comment] 2018-09-01 12:42
Closing issue due to lack of information.

**Comment by sundeepsqa** [comment] 2018-09-10 00:52
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>nz.co.iag.dms</groupId>
	<artifactId>test-automation</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>DMS Test Automation</name>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<unit-test-names>all-unit-tests</unit-test-names>
		<automation-test-names>all-automation-tests</automation-test-names>
		<environment>systest</environment>
		<queue>business</queue>
	</properties>
	<build>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.feature</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.21.0</version>
				<configuration>
					<suiteXmlFiles>
						<suiteXmlFile>src/test/resources/unit-tests.xml</suiteXmlFile>
					</suiteXmlFiles>
					<properties>
						<property>
							<name>testnames</name>
							<value>${unit-test-names}</value>
						</property>
					</properties>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.21.0</version>
				<configuration>
					<suiteXmlFiles>
						<suiteXmlFile>src/main/resources/automation-tests.xml</suiteXmlFile>
					</suiteXmlFiles>
					<properties>
						<property>
							<name>testnames</name>
							<value>${automation-test-names}</value>
						</property>
					</properties>
				</configuration>
				<executions>
					<execution>
						<id>integration-test</id>
						<phase>integration-test</phase>
						<goals>
							<goal>integration-test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<mainClass>nz.co.iag.dms.test.automation.inbound.common.Main</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>
	
	<repositories>
    	<repository>
      		<id>jcenter</id>
      		<url>https://jcenter.bintray.com/</url>
    	</repository>
	</repositories>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
  			<groupId>io.github.prashant-ramcharan</groupId>
  			<artifactId>courgette-jvm</artifactId>
  			<version>2.4.3</version>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
		</dependency>
		
		<dependency>
    		<groupId>commons-io</groupId>
    		<artifactId>commons-io</artifactId>
    		<version>2.6</version>
		</dependency>		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.ews-java-api</groupId>
			<artifactId>ews-java-api</artifactId>
			<version>2.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.3</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>6.4.0.jre8</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>		
		
		<dependency>
    		<groupId>org.apache.commons</groupId>
    		<artifactId>commons-io</artifactId>
    		<version>1.3.2</version>
		</dependency>
		
	
	</dependencies>
</project>
`

**Comment by sundeepsqa** [comment] 2018-09-10 00:54
Hi Prashant,

I have just added the repository and dependency into POM.xml:

<repositories>
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
</repositories>

<dependency>
  <groupId>io.github.prashant-ramcharan</groupId>
  <artifactId>courgette-jvm</artifactId>
  <version>2.4.3</version>
</dependency>

**Comment by sundeepsqa** [comment] 2018-09-10 01:05
Complete POM.xml is here:
[pom.pdf](https://github.com/prashant-ramcharan/courgette-jvm/files/2364841/pom.pdf)

**Comment by prashant-ramcharan** [comment] 2018-09-10 06:42
Hi @sundeepsqa 

Looks like you still including version 1.2.5 of Cucumber in your POM xml.

Please **remove all** dependancies of Cucumber in your POM xml.

Courgette already has a dependancy on Cucumber so there's no need to add Cucumber dependancies to your POM xml.

**Comment by prashant-ramcharan** [comment] 2018-09-10 06:44
Also, Cucumber 2.4.3 is added to Maven Central so there's no need to add the JCenter repo in your POM xml if you don't want to.

**Comment by sundeepsqa** [comment] 2018-09-10 23:50
I have removed all cucumber dependencies but I still see the problem. I've attached the latest pom
[pom.pdf](https://github.com/prashant-ramcharan/courgette-jvm/files/2368811/pom.pdf)

**Comment by prashant-ramcharan** [comment] 2018-09-11 17:40
I've added an example project here: https://github.com/prashant-ramcharan/courgette-jvm-maven-example

Please clone and import as Maven project.

**Comment by sundeepsqa** [comment] 2018-09-11 21:41
Thanks Prashant, I will try it and let you know.

**Comment by sundeepsqa** [comment] 2018-09-12 22:57
Hi Prashant,
Your project that you shared works fine but I still have the same issue with my project. 
I'm using TestNG runner instead of Junit Runner, do you think that can be the issue? I cant change it Junit runner in my project since i have a lot of dependencies on TestNG runner.

**Comment by prashant-ramcharan** [comment] 2018-09-13 06:45
I just tested it with the Courgette TestNG runner in the maven example project and it works fine.

Pull branch: https://github.com/prashant-ramcharan/courgette-jvm-maven-example/tree/testng-example

Unfortunately, without seeing your project or being able to reproduce your issue, I'm unable to investigate further.

**Comment by prashant-ramcharan** [comment] 2018-09-16 20:40
Closing this issue. 

Please re-open if you can provide a project whereby you can replicate your issue.

**Closed by prashant-ramcharan** 2018-09-16 20:40 UTC
