### ISSUE TITLE
Courgette does not finish test run after running all test with  given tags

### ISSUE THREAD

**Issue by ThisComarero** [prashant-ramcharan/courgette-jvm#364] opened 2022-12-09 08:01 UTC
Hello,

I am using courgette in my project from last year, and recently I have started facing new issue.  From time to time my courgette test run runs twice in one jenkins build. Once courgette runs all the test be given tag, and then proces does not finish but runs again all the test in the repository no matter which tag there have (It's looks like some default courgette command is run). Sometimes it fails before it runs all the test (I set the time limit for jenkins build).I was able to reproduce it on jenkins with normal test run, locally and even with cucumber dry run. I have no idea what can cause this problem. 

I have noticed during full debug run two exceptions before courgette starts second run

```
java.lang.IllegalThreadStateException: process hasn't exited
	at java.base/java.lang.ProcessImpl.exitValue(ProcessImpl.java:521)
	at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:42)
	at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:244)
	at courgette.runtime.CourgetteRunner.lambda$run$3(CourgetteRunner.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
	
```
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:328)
	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
	at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:34)
	at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:244)
	at courgette.runtime.CourgetteRunner.lambda$run$3(CourgetteRunner.java:82)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I have noticed that this issue affect runs where there is a lot of test. I was not saw this on my build with smaller ammout of test ~50.
My runner which runs the most tests has more than 700. Test are run in 12 threads with 2 reruns.

Another thing I have noticed is in the test report. Result are spitted into two sections in the allure report (depends on path?) 
![2022-12-09_08h57_22](https://user-images.githubusercontent.com/26418022/206653227-e0f9ce8a-2c2b-4695-856b-6ef539b2bd61.png)

In my project I have over 2000 scenarios split to different modules and stages (by severity). I have around 1300 scenarios automated already, and other scenarios are in repository as a part of documentation. 

In my project I use
Courgette version: 6.8.0
Gradle version: 6.8.1

**Comment by prashant-ramcharan** [comment] 2022-12-13 18:34
Hello, 

It seems something is terminating the JVM before Courgette is able to complete. Do you use `System.exit()` in your project or have any dependencies that calls `exit()` on the JVM?

Does this also happen when you **don't rerun** failed scenarios?

I have projects that run large volume of tests without issues and I've not been able to reproduce this. Are you able to provide an example project to reproduce this?

**Comment by MBogdanski** [comment] 2023-01-23 08:46
So, I tried to debug it a little bit, and maybe found a clue what can be the issue. 
First of all, the issue is, that Courgette is executing another build of tests, meanwhile existing build (it occur on the end of the build, or in the middle of the build)
![image](https://user-images.githubusercontent.com/21061874/213996434-2002282d-d151-45d3-998e-5ed27e3ba72f.png)
As you can see, there are 2 packages which were executed (src/test/resources/features is correct one, second features/bom is package from features, it will take anothers packages, but we have timeout set to our build, so other packages are not executed further).
When you look on timeline, we can see, that another build started executing without parallel
![image](https://user-images.githubusercontent.com/21061874/213996738-71be5e0c-9196-4ac0-835e-76ad9bbadc58.png)
![image](https://user-images.githubusercontent.com/21061874/213996806-e55f686a-1e75-49b9-a8cd-a45ad3d5df1d.png)
On this build, this occured twice.
So we tried to find the issue, and on 99% we can confirm, that issue only occur when we have used retries failed scenarios.
I started investigating it and found, that sometimes featureUri to rerun (which is path to Feature file) is empty, because rerun file was empty:
![image](https://user-images.githubusercontent.com/21061874/213997278-489cf9a7-7e11-4213-a997-df52d816ca6e.png)
So maybe on CourgetteFeatureRunner, when process is executed with empty String featureUri, Cucumber is taking all Feature Files which he can find by default and that's why he execute all of the tests once again? 
![image](https://user-images.githubusercontent.com/21061874/213997590-3ae31b7e-e2e1-40f1-bc1e-8171e53f6546.png)
Here it will be builder.command.get(108) -> on this index featureUri is stored.
Can you please check it? If you want I can participate on it, just let me know and we can discuss it more on some Hangouts or another communicator.
@prashant-ramcharan

**Comment by prashant-ramcharan** [comment] 2023-01-23 14:11
Hi @MBogdanski , thanks for debugging and narrowing it down. 

I assume you using `CourgetteRunLevel.SCENARIO` ?  

You _shouldn't_ get this issue when using `CourgetteRunLevel.FEATURE`  because the `cucumberArgs` are re-used instead of `rerunArags`

I will provide a fix for this.

**Comment by MBogdanski** [comment] 2023-01-23 15:03
Hi @prashant-ramcharan , yes, exactly, we are using `CourgetteRunLevel.SCENARIO`

**Comment by prashant-ramcharan** [comment] 2023-01-27 17:35
Hi, this is now resolved in Courgette `6.9.0`

**Comment by MBogdanski** [comment] 2023-01-29 17:02
Hi, thanks @prashant-ramcharan, I will test if this resolve the issue, and will let you know the result

**Comment by MBogdanski** [comment] 2023-02-03 12:36
Hi, @prashant-ramcharan, looks like bug is resolved :) thanks for your support!

**Comment by prashant-ramcharan** [comment] 2023-02-06 09:52
No problem 👍

**Closed by prashant-ramcharan** 2023-02-06 09:52 UTC
