### ISSUE TITLE
Reports are not saved when reportTargetDir option takes a directory structure value

### ISSUE THREAD

**Issue by bocobogna** [prashant-ramcharan/courgette-jvm#417] opened 2024-09-25 08:52 UTC
I noticed that since version 6.14, reports are not saved when the reportTargetDir option is a directory structure. 
When reportTargetDir = “build” creating directory structure and files inside works smoothly, build/courgette-report and build/cucumber-report along with files inside are saved correctly.
The problem occurs when the reportTargetDir option takes a directory structure value, such as reportTargetDir = “build/courgette”.
The courgette directory is not created and consequently the entire structure inside is not created either.
As far as I have glanced at the code, the solution seems to be to use mkdirs() instead of mkdir() in the FileUtils class in createDirectory() and createFile() methods.

**Comment by prashant-ramcharan** [comment] 2024-09-25 18:06
I'm unable to reproduce this. 

Using ` reportTargetDir = "build/courgette"` works fine for me. 

(_the build directory was deleted before the test ran_)

<img width="1256" alt="Screenshot 2024-09-25 at 19 03 59" src="https://github.com/user-attachments/assets/680531c7-c0bc-4d7a-bbb2-4607ac10e888">


Do you see any errors in the console?

**Comment by bocobogna** [comment] 2024-09-25 19:26
We get an error:
`pl.sii.eu.puma.runner.CourgetteSmokeRunner > executionError FAILED
    courgette.runtime.CourgetteException at FileUtils.java:143
`
![2024-09-25_21h06_15](https://github.com/user-attachments/assets/61c1779b-6767-49b6-9658-9504a9b75b1c)

**Comment by prashant-ramcharan** [comment] 2024-09-26 06:33
Thanks, I will put a fix for this.

**Comment by prashant-ramcharan** [comment] 2024-09-26 07:33
This is now released in version `6.17.0`

**Closed** 2024-10-02 06:24 UTC
